<?php

namespace AppBundle\Repository;

/**
 * cervezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cervezaRepository extends \Doctrine\ORM\EntityRepository
{
}
