<?php

namespace AppBundle\Repository;

/**
 * usuario_beer_mappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuario_beer_mappingRepository extends \Doctrine\ORM\EntityRepository
{
}
